exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# Site metadata
title: "analytics.psd401.net | The Peninsula School District's web traffic."
description: "Official data on web traffic to all Peninsula SD websites. Published by the Technical Services Department."

# site's own URL, and data root
url: https://analytics.psd401.net
data_url: https://analytics.psd401.net/data

# GitHub information
org_name: psd401
repo_name: analytics.psd401.net

# twitter information
twitter: psdts
